### ISSUE TITLE
Please remove (indirect) dependency on List::MoreUtils

### ISSUE THREAD

**Issue by plicease** [Grinnz/Perl-Critic-Community#54]
`[Community::PreferredAlternatives]` (rightly) discourages `List::MoreUtils` in favor of `List::SomeUtils` and others, but this dist itself indirectly depends on `List::MoreUtils` via `[Community::ArrayAssignAref]` and `Perl-Critic-Pulp`.  Now that `Perl::Critic` itself and friends no longer depend on LMU this is the only remaining dependency I (and probably others) have on LMU.  And the inherited policy isn't even one of the policies in PCP that even uses LMU.

I've opened this ticket on `Perl-Critic-Pulp` here: https://rt.cpan.org/Public/Bug/Display.html?id=151977 and it remains unanswered.

**Comment by Grinnz** [comment]
Closed by #55
